package com.example.b2cmarket.ElonActivity

import android.app.Activity
import android.content.Intent
import android.net.Uri
import android.os.Bundle
import android.view.View
import android.widget.Toast
import androidx.appcompat.app.AppCompatActivity
import com.example.b2cmarket.databinding.ActivityElonBinding
import com.google.firebase.storage.FirebaseStorage
import com.google.firebase.storage.StorageReference
import java.util.UUID


class ElonActivity : AppCompatActivity() {
    private val binding by lazy { ActivityElonBinding.inflate(layoutInflater) }
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(binding.root)
        binding.imageAdd.setOnClickListener {
            val intent = Intent(Intent.ACTION_PICK)
            intent.type = "image/*"
            startActivityForResult(intent, 1)
        }

        binding.btnSaqlash.setOnClickListener {
            binding.loadingView.visibility= View.VISIBLE
            if (!binding.textView2.text.toString().isNullOrEmpty()){
                if (!binding.edtProductName.text.toString().isNullOrEmpty()){
                    if (!binding.edtProductPrice.text.toString().isNullOrEmpty()){
                        if (!binding.edtProductIzoh.text.toString().isNullOrEmpty()){
                            val storage = FirebaseStorage.getInstance()
                            val autoGeneratedId = generateAutoId()
                            val storageRef: StorageReference = storage.getReference("/Rasmlar").child("$autoGeneratedId")
// Avtomatik ravishda yangi id generatsiya qilamiz


                            val uploadTask = storageRef.putFile(Uri.parse(binding.textView2.text.toString()))

                            uploadTask.addOnSuccessListener { taskSnapshot ->
                                binding.loadingView.visibility= View.GONE
                                Toast.makeText(this, "Yuklandi", Toast.LENGTH_SHORT).show()
                                storageRef.downloadUrl.addOnSuccessListener { uri ->
                                    val downloadUrl = uri.toString()
                                }
                            }.addOnFailureListener {
                                binding.loadingView.visibility= View.GONE
                                Toast.makeText(this, "Xatolik", Toast.LENGTH_SHORT).show()
                                // Task muvaffaqiyatsiz tugab qoldi
                            }

                        }

                    }
                }
            }
            else{
                Toast.makeText(this, "Rasm tanlanmagan", Toast.LENGTH_SHORT).show()
            }
        }


    }
    // Galereyadan tanlangan rasmni olish uchun
    override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
        super.onActivityResult(requestCode, resultCode, data)

        if (requestCode == 1 && resultCode == Activity.RESULT_OK && data != null) {
            val selectedImage = data.data
            binding.textView2.text=selectedImage.toString()
            binding.imageAdd.setImageURI(selectedImage)
        }
    }
    fun generateAutoId(): String {
        return UUID.randomUUID().toString()
    }

}